ghc
haskell-random
haskell-dataenc
haskell-html
haskell-tar
haskell-extensible-exceptions
haskell-zlib
haskell-syb
haskell-transformers
haskell-mtl
haskell-text
haskell-parsec
haskell-terminfo
haskell-regex-base
haskell-utf8-string
haskell-haskeline
haskell-mmap
haskell-hashed-storage
haskell-network
haskell-HTTP
haskell-regex-posix
haskell-regex-compat
haskell-primitive
haskell-vector
darcs
