ghc
haskell-hostname
haskell-ansi-terminal
haskell-random
haskell-extensible-exceptions
haskell-ansi-wl-pprint
haskell-transformers
haskell-mtl
haskell-regex-base
haskell-regex-posix
haskell-text
haskell-xml
haskell-test-framework