pysetuptools
MySQL-python
perl-Params-Validate
libcdaudio
perl-List-MoreUtils
perl-lwp-mediatypes
perl-JSON
urlgrabber
jdk
perl-Params-Util
python-oauth
perl-http-date
perl-file-listing
perl-IO-HTML
perl-Try-Tiny
perl-Task-Weaken
lame
perl-XML-XPath
xvidcore
dcraw
libmp4v2
faac
libvpx
perl-Socket6
perl-IO-Socket-INET6
BeautifulSoup
lxml
perl-Devel-Symdump
perl-Pod-Coverage
perl-Test-Pod-Coverage
perl-Class-Singleton
perl-DateTime-Locale
perl-www-robotrules
perl-Test-Requires
dvdauthor
perl-html-tagset
perl-html-parser
x264
perl-Test-Fatal
perl-Package-Stash-XS
perl-encode-locale
perl-http-message
perl-http-negotiate
perl-http-cookies
perl-http-daemon
perl-Image-Size
perl-Math-Round
perl-Sub-Uplevel
perl-net-http
libwww-perl
perl-Test-Pod
perl-Params-Classify
perl-Module-Runtime
perl-Sub-Install
perl-Data-OptList
perl-Sub-Exporter
perl-Dist-CheckConflicts
perl-Package-DeprecationManager
perl-Package-Stash
perl-Class-Load
perl-DateTime-TimeZone
perl-Test-Exception
perl-DateTime
perl-DateTime-Format-Strptime
perl-Net-UPnP
mythtv
perl-Class-Factory-Util
perl-DateTime-Format-Builder
perl-DateTime-Format-ISO8601
mythplugins
