ghc
haskell-base64-bytestring
haskell-digest
haskell-random
haskell-extensible-exceptions
haskell-zlib
haskell-dlist
haskell-syb
haskell-pandoc-types
haskell-transformers
haskell-mtl
haskell-text
haskell-blaze-builder
haskell-blaze-markup
haskell-parsec
haskell-xml
haskell-json
haskell-regex-base
haskell-regex-pcre-builtin
haskell-utf8-string
haskell-temporary
haskell-texmath
haskell-citeproc-hs
haskell-blaze-html
haskell-highlighting-kate
haskell-data-default
haskell-network
haskell-tagsoup
haskell-HTTP
haskell-zip-archive
pandoc