perl-http-date
perl-file-listing
perl-IO-HTML
Net-SSLeay
perl-net-http
perl-Mozilla-CA
perl-lwp-mediatypes
perl-html-tagset
perl-Net-LibIDN
perl-www-robotrules
perl-encode-locale
perl-IO-Socket-SSL
perl-html-parser
perl-http-message
perl-http-daemon
perl-http-cookies
perl-http-negotiate
libwww-perl
perl-LWP-Protocol-https