perl-http-date
perl-file-listing
perl-IO-HTML
perl-net-http
perl-tk
perl-lwp-mediatypes
perl-html-tagset
perl-www-robotrules
perl-encode-locale
perl-html-parser
perl-http-message
perl-http-daemon
perl-http-cookies
perl-http-negotiate
libwww-perl
perlprimer
