perl-Sub-Uplevel
perl-http-date
perl-file-listing
perl-IO-HTML
perl-net-http
perl-lwp-mediatypes
perl-html-tagset
perl-http-server-simple
perl-tree-dagnode
perl-test-warn
perl-www-robotrules
perl-encode-locale
perl-html-parser
perl-http-message
perl-http-negotiate
perl-html-form
perl-http-cookies
perl-http-daemon
libwww-perl
perl-http-response-encoding
perl-www-mechanize
