gnome-mime-data
perl-Sub-Uplevel
perl-extutils-depends
perl-tree-dagnode
gtkimageview
perl-lwp-mediatypes
locale-gettext
perl-http-date
perl-file-listing
perl-IO-HTML
perl-net-http
perl-xml-twig
perl-net-dbus
perl-extutils-pkgconfig
perl-x11-protocol
ORBit2
libbonobo
libgnomecanvas
perl-www-robotrules
perl-proc-processtable
perl-glib
perl-gnome2-gconf
perl-test-warn
perl-html-tagset
gnome-vfs
perl-gnome2-vfs
libgnome
libbonoboui
libgnomeui
perl-encode-locale
perl-cairo
perl-pango
perl-gtk2
perl-gnome2-canvas
perl-gnome2
perl-gtk2-imageview
perl-gnome2-wnck
perl-html-parser
perl-http-message
perl-http-negotiate
perl-html-form
perl-http-cookies
perl-http-daemon
libwww-perl
perl-http-response-encoding
perl-http-server-simple
perl-www-mechanize
shutter
