perl-Net-Server
perl-Geography-Countries
perl-Encode-Detect
perl-lwp-mediatypes
perl-Net-LibIDN
re2c
Net-SSLeay
perl-http-date
perl-file-listing
perl-IO-HTML
perl-Net-DNS-Resolver-Programmable
perl-Image-Info
perl-IO-Socket-SSL
perl-IP-Country
perl-net-ip
pyzor
perl-Crypt-OpenSSL-Random
perl-Crypt-OpenSSL-Bignum
perl-Socket6
perl-IO-Socket-INET6
perl-NetAddr-IP
perl-html-tagset
perl-Net-Ident
perl-www-robotrules
perl-TimeDate
perl-Crypt-OpenSSL-RSA
perl-net-http
perl-digest-sha1
perl-digest-hmac
perl-net-dns
perl-Mail-SPF
perl-MailTools
perl-Mail-DKIM
perl-encode-locale
perl-html-parser
perl-http-message
perl-http-negotiate
perl-http-daemon
perl-http-cookies
libwww-perl
spamassassin