perl-extutils-depends
perl-Sub-Uplevel
perl-lwp-mediatypes
perl-Text-Glob
locale-gettext
perl-http-date
perl-file-listing
perl-IO-HTML
perl-net-http
clamav
perl-extutils-pkgconfig
perl-glib
perl-net-ip
perl-html-tagset
perl-www-robotrules
perl-Number-Compare
perl-File-Find-Rule
perl-Test-Exception
perl-digest-sha1
perl-digest-hmac
perl-net-dns
perl-Carp-Clan
perl-Bit-Vector
perl-Date-Calc
perl-encode-locale
perl-cairo
perl-pango
perl-gtk2
perl-html-parser
perl-http-message
perl-http-negotiate
perl-http-daemon
perl-http-cookies
libwww-perl
clamtk
thunar-sendto-clamtk