perl-TermReadKey
perl-lwp-mediatypes
perl-Test-Inter
perl-http-date
perl-file-listing
perl-IO-HTML
perl-www-robotrules
perl-net-http
perl-Class-MethodMaker
perl-Lingua-EN-Numbers-Ordinate
perl-xml-twig
perl-XML-Writer
perl-XML-NamespaceSupport
perl-html-tagset
perl-XML-SAX-Base
perl-yaml
perl-Unicode-String
perl-Term-ProgressBar
perl-Lingua-Preferred
perl-YAML-Syck
perl-xml-sax
perl-xml-libxml
perl-File-Slurp
perl-Devel-Symdump
perl-Pod-Coverage
perl-Test-Pod-Coverage
perl-Test-Pod
perl-Date-Manip
perl-encode-locale
perl-html-parser
perl-http-message
perl-http-negotiate
perl-http-daemon
perl-http-cookies
libwww-perl
xmltv